// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkKh1lEG9Ca6CFWv_TGBI387F4hT1Wg0',
    appId: '1:5418053022:web:c4182fab13e63b3c567a8f',
    messagingSenderId: '5418053022',
    projectId: 'pratice-project-1403',
    authDomain: 'pratice-project-1403.firebaseapp.com',
    storageBucket: 'pratice-project-1403.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2P5iZxKLgpwdLQ_4SSYVES3fy-SFDTgE',
    appId: '1:5418053022:android:a34698830efdfda8567a8f',
    messagingSenderId: '5418053022',
    projectId: 'pratice-project-1403',
    storageBucket: 'pratice-project-1403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTeXqClP9qPCRK4Jd486eeJ9IwRJP2noA',
    appId: '1:5418053022:ios:d927cc58071b10d4567a8f',
    messagingSenderId: '5418053022',
    projectId: 'pratice-project-1403',
    storageBucket: 'pratice-project-1403.appspot.com',
    iosBundleId: 'com.example.otpAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTeXqClP9qPCRK4Jd486eeJ9IwRJP2noA',
    appId: '1:5418053022:ios:134a9298b16182dc567a8f',
    messagingSenderId: '5418053022',
    projectId: 'pratice-project-1403',
    storageBucket: 'pratice-project-1403.appspot.com',
    iosBundleId: 'com.example.otpAuth.RunnerTests',
  );
}
